In [3]:
# import libraries
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

### 1) Generate Our Bracket Predictions

In [4]:
# read in the dataset
teams = pd.read_csv("datasets/kaggle_data/Teams.csv")
seeds = pd.read_csv("datasets/kaggle_data/TourneySeeds.csv")
slots = pd.read_csv("datasets/kaggle_data/TourneySlots.csv")

In [5]:
seeds.head()

   Season Seed  Team
0    1985  W01  1207
1    1985  W02  1210
2    1985  W03  1228
3    1985  W04  1260
4    1985  W05  1374

In [6]:
slots.head()

   Season  Slot Strongseed Weakseed
0    1985  R1W1        W01      W16
1    1985  R1W2        W02      W15
2    1985  R1W3        W03      W14
3    1985  R1W4        W04      W13
4    1985  R1W5        W05      W12

In [3]:
# filtration function
def filter_season(data, season):
    return data[data["Season"] == season]
    
def filter_into_seasons(data):
    # buffer to hold list of seasons
    season_arr = []
    
    # min and max
    max_season = data["Season"].max()
    min_season = data["Season"].min()
    
    # filter
    for season in range(min_season, max_season + 1):
        season_arr.append(filter_season(data, season))
        
    return season_arr

In [4]:
seeds_arr = filter_into_seasons(seeds)

In [122]:
slots_arr = filter_into_seasons(slots)

In [487]:
# tournament class
class Tournament(object):
    # init function
    def __init__(self, seeds, slots, model):
        self.seeds = seeds
        self.slots = slots
        self.model = model
        
        games = []
       
        round_1_slots = slots[slots["Slot"].str.contains("R1")]
        
        # generate first round games
        for index, slot in round_1_slots.iloc[:32, :].iterrows():
            # get seeds
            team_1_seed = slot["Strongseed"]
            team_2_seed = slot["Weakseed"] 

            # teams
            team_1 = seeds.loc[seeds["Seed"] == team_1_seed, "TeamID"].values[0]
            team_2 = seeds.loc[seeds["Seed"] == team_2_seed, "TeamID"].values[0]
            
            # predict winner under our model
            cur_game_pred_team = self.model.predict(team_1, team_2)

            # predict winner seed under our model
            if cur_game_pred_team ==  team_1:
                cur_game_pred_seed = team_1_seed
            else:
                cur_game_pred_seed = team_2_seed

            # append games
            games.append((slot["Slot"], 
                          team_1_seed, 
                          team_1, 
                          team_2_seed, 
                          team_2, 
                          cur_game_pred_team, 
                          cur_game_pred_seed))

        # convert to datafram
        self.round_1_df = pd.DataFrame(data=np.array(games), 
                                       columns=["Slot", 
                                                "Strongseed", 
                                                "Strongseed Team", 
                                                "Weakseed", 
                                                "Weekseed Team", 
                                                "Prediction", 
                                                "Prediction Seed"])
        
        self.round_2_df = pd.DataFrame()
        self.round_3_df = pd.DataFrame()
        self.round_4_df = pd.DataFrame()
        self.round_5_df = pd.DataFrame()
        self.round_6_df = pd.DataFrame()
            
    
    # run a particular round
    def generate_round_games(self, round_n):
        games = []
        
        n_games_in_prev_round = {2: 32, 3: 16, 4: 8, 5:4, 6:2}
        
        prev_round_df_dic = {2: self.round_1_df,
                         3: self.round_2_df,
                         4: self.round_3_df,
                         5: self.round_4_df,
                         6: self.round_5_df}
    
        # slots of previous round
        round_n_slots = self.slots[self.slots["Slot"].str.contains("R{}".format(round_n))]
        
        # prev round df
        prev_round_df = prev_round_df_dic.get(round_n)
        
        # generate first round games
        for index, slot in round_n_slots.iloc[:n_games_in_prev_round.get(round_n), :].iterrows():
            # get seeds
            team_1_seed = slot["StrongSeed"]
            team_2_seed = slot["WeakSeed"]
            

            # teams
            team_1 = prev_round_df.loc[prev_round_df["Slot"] == team_1_seed, "Prediction"].values[0]
            team_2 = prev_round_df.loc[prev_round_df["Slot"] == team_2_seed, "Prediction"].values[0]

            # predict winner under our model
            cur_game_pred_team = self.model.predict(team_1, team_2)

            # predict winner seed under our model
            if cur_game_pred_team ==  team_1:
                cur_game_pred_seed = team_1_seed
            else:
                cur_game_pred_seed = team_2_seed

            # append games
            games.append((slot["Slot"], 
                          team_1_seed, 
                          team_1, 
                          team_2_seed, 
                          team_2, 
                          cur_game_pred_team, 
                          cur_game_pred_seed))

        # convert to datafram
        cur_round_df = pd.DataFrame(data=np.array(games), 
                                       columns=["Slot", 
                                                "StrongSeed", 
                                                "Strongseed Team", 
                                                "WeakSeed", 
                                                "Weekseed Team", 
                                                "Prediction", 
                                                "Prediction Seed"])
        
        if round_n == 2:
            self.round_2_df = cur_round_df
        elif round_n == 3:
            self.round_3_df = cur_round_df
        elif round_n == 4:
            self.round_4_df = cur_round_df
        elif round_n == 5:
            self.round_5_df = cur_round_df
        elif round_n == 6:
            self.round_6_df = cur_round_df  
     
    # simulate an entire tournament
    def simulate_tournament(self):  
        for n in range(2,7):
            self.generate_round_games(n)
            
        self.entire_bracket = pd.concat([self.round_1_df, 
                                              self.round_2_df,
                                              self.round_3_df,
                                              self.round_4_df,
                                              self.round_5_df,
                                              self.round_6_df])
        self.entire_bracket.reset_index(inplace = True, drop=True)

In [488]:
class Predictor_Basic(object):
    # init function
    def __init__(self):
        return
    
    def predict(self, team_1, team_2):
        return team_2

In [489]:
seeds_1985 = seeds_arr[0]
slots_1985 = slots_arr[0]

In [490]:
# test
tourney_1985 = Tournament(seeds_1985, slots_1985, Predictor_dBasic())
tourney_1985.simulate_tournament()

In [491]:
tourney_1985.entire_bracket

,Slot,Strongseed,Strongseed Team,Weakseed,Weekseed Team,Prediction,Prediction Seed
0,R1W1,W01,1207,W16,1250,1250,W16
1,R1W2,W02,1210,W15,1273,1273,W15
2,R1W3,W03,1228,W14,1318,1318,W14
3,R1W4,W04,1260,W13,1233,1233,W13
4,R1W5,W05,1374,W12,1330,1330,W12
5,R1W6,W06,1208,W11,1455,1455,W11
6,R1W7,W07,1393,W10,1177,1177,W10
7,R1W8,W08,1396,W09,1439,1439,W09
8,R1X1,X01,1385,X16,1380,1380,X16
9,R1X2,X02,1433,X15,1267,1267,X15
10,R1X3,X03,1301,X14,1305,1305,X14
11,R1X4,X04,1424,X13,1361,1361,X13
12,R1X5,X05,1449,X12,1246,1246,X12
13,R1X6,X06,1409,X11,1431,1431,X11
14,R1X7,X07,1104,X10,1112,1112,X10
15,R1X8,X08,1234,X09,1116,1116,X09
16,R1Y1,Y01,1328,Y16,1299,1299,Y16
17,R1Y2,Y02,1272,Y15,1335,1335,Y15
18,R1Y3,Y03,1181,Y14,1337,1337,Y14
19,R1Y4,Y04,1326,Y13,1235,1235,Y13
20,R1Y5,Y05,1256,Y12,1338,1338,Y12
21,R1Y6,Y06,1403,Y11,1130,1130,Y11
22,R1Y7,Y07,1412,Y10,1277,1277,Y10
23,R1Y8,Y08,1425,Y09,1229,1229,Y09
24,R1Z1,Z01,1276,Z16,1192,1192,Z16
25,R1Z2,Z02,1314,Z15,1292,1292,Z15
26,R1Z3,Z03,1242,Z14,1325,1325,Z14
27,R1Z4,Z04,1261,Z13,1298,1298,Z13
28,R1Z5,Z05,1268,Z12,1275,1275,Z12
29,R1Z6,Z06,1345,Z11,1120,1120,Z11
...,...,...,...,...,...,...,...
33,R2W2,R1W2,1273,R1W7,1177,1177,R1W7
34,R2W3,R1W3,1318,R1W6,1455,1455,R1W6
35,R2W4,R1W4,1233,R1W5,1330,1330,R1W5
36,R2X1,R1X1,1380,R1X8,1116,1116,R1X8
37,R2X2,R1X2,1267,R1X7,1112,1112,R1X7
38,R2X3,R1X3,1305,R1X6,1431,1431,R1X6
39,R2X4,R1X4,1361,R1X5,1246,1246,R1X5
40,R2Y1,R1Y1,1299,R1Y8,1229,1229,R1Y8
41,R2Y2,R1Y2,1335,R1Y7,1277,1277,R1Y7
42,R2Y3,R1Y3,1337,R1Y6,1130,1130,R1Y6
43,R2Y4,R1Y4,1235,R1Y5,1338,1338,R1Y5
44,R2Z1,R1Z1,1192,R1Z8,1173,1173,R1Z8
45,R2Z2,R1Z2,1292,R1Z7,1333,1333,R1Z7
46,R2Z3,R1Z3,1325,R1Z6,1120,1120,R1Z6
47,R2Z4,R1Z4,1298,R1Z5,1275,1275,R1Z5
48,R3W1,R2W1,1439,R2W4,1330,1330,R2W4
49,R3W2,R2W2,1177,R2W3,1455,1455,R2W3
50,R3X1,R2X1,1116,R2X4,1246,1246,R2X4
51,R3X2,R2X2,1112,R2X3,1431,1431,R2X3
52,R3Y1,R2Y1,1229,R2Y4,1338,1338,R2Y4
53,R3Y2,R2Y2,1277,R2Y3,1130,1130,R2Y3
54,R3Z1,R2Z1,1173,R2Z4,1275,1275,R2Z4
55,R3Z2,R2Z2,1333,R2Z3,1120,1120,R2Z3
56,R4W1,R3W1,1330,R3W2,1455,1455,R3W2
57,R4X1,R3X1,1246,R3X2,1431,1431,R3X2
58,R4Y1,R3Y1,1338,R3Y2,1130,1130,R3Y2
59,R4Z1,R3Z1,1275,R3Z2,1120,1120,R3Z2
60,R5WX,R4W1,1455,R4X1,1431,1431,R4X1
61,R5YZ,R4Y1,1130,R4Z1,1120,1120,R4Z1
62,R6CH,R5WX,1431,R5YZ,1120,1120,R5YZ

In [377]:
tourney_1985.round_2_df.head()

,Slot,Strongseed,Strongseed Team,Weakseed,Weekseed Team,Prediction,Prediction Seed
0,R2W1,R1W1,1250,R1W8,1439,1439,R1W8
1,R2W2,R1W2,1273,R1W7,1177,1177,R1W7
2,R2W3,R1W3,1318,R1W6,1455,1455,R1W6
3,R2W4,R1W4,1233,R1W5,1330,1330,R1W5
4,R2X1,R1X1,1380,R1X8,1116,1116,R1X8

In [378]:
tourney_1985.round_3_df.head()

,Slot,Strongseed,Strongseed Team,Weakseed,Weekseed Team,Prediction,Prediction Seed
0,R3W1,R2W1,1439,R2W4,1330,1330,R2W4
1,R3W2,R2W2,1177,R2W3,1455,1455,R2W3
2,R3X1,R2X1,1116,R2X4,1246,1246,R2X4
3,R3X2,R2X2,1112,R2X3,1431,1431,R2X3
4,R3Y1,R2Y1,1229,R2Y4,1338,1338,R2Y4

In [379]:
tourney_1985.round_4_df.head()

,Slot,Strongseed,Strongseed Team,Weakseed,Weekseed Team,Prediction,Prediction Seed
0,R4W1,R3W1,1330,R3W2,1455,1455,R3W2
1,R4X1,R3X1,1246,R3X2,1431,1431,R3X2
2,R4Y1,R3Y1,1338,R3Y2,1130,1130,R3Y2
3,R4Z1,R3Z1,1275,R3Z2,1120,1120,R3Z2

In [380]:
tourney_1985.round_5_df.head()

,Slot,Strongseed,Strongseed Team,Weakseed,Weekseed Team,Prediction,Prediction Seed
0,R5WX,R4W1,1455,R4X1,1431,1431,R4X1
1,R5YZ,R4Y1,1130,R4Z1,1120,1120,R4Z1

In [374]:
tourney_1985.round_6_df.head()

,Slot,Strongseed,Strongseed Team,Weakseed,Weekseed Team,Prediction,Prediction Seed
0,R6CH,R5WX,1431,R5YZ,1120,1120,R5YZ

---

### 2) Generate Actual Bracket

In [383]:
tourney_games = pd.read_csv("datasets/kaggle_data/TourneyCompactResults.csv")

In [384]:
tourney_games.head()

   Season  Daynum  Wteam  Wscore  Lteam  Lscore Wloc  Numot
0    1985     136   1116      63   1234      54    N      0
1    1985     136   1120      59   1345      58    N      0
2    1985     136   1207      68   1250      43    N      0
3    1985     136   1229      58   1425      55    N      0
4    1985     136   1242      49   1325      38    N      0

In [492]:
tourney_arr = filter_into_seasons(tourney_games)

In [493]:
tourney_1985 = tourney_arr[0]
seeds_1985 = seeds_arr[0]

In [494]:
class ActualTournament(object):
    # init function
    def __init__(self, data):
        self.tourney = data
        return
    
    def predict(self, team_1, team_2):
        game_played_team_1_win = self.tourney[(self.tourney["Wteam"] == int(team_1)) & (self.tourney["Lteam"] == int(team_2))]
        game_played_team_2_win = self.tourney[(self.tourney["Lteam"] == int(team_1)) & (self.tourney["Wteam"] == int(team_2))]
        
        if game_played_team_1_win.shape[0] == 1:
            return team_1
        elif game_played_team_2_win.shape[0] == 1:
            return team_2
        else:
            print "Error"
            return -1

In [495]:
actual_1985_tourney = Tournament(seeds_1985, slots_1985, ActualTournament(tourney_1985))

In [496]:
actual_1985_tourney.simulate_tournament()

In [497]:
actual_1985_tourney.entire_bracket

,Slot,Strongseed,Strongseed Team,Weakseed,Weekseed Team,Prediction,Prediction Seed
0,R1W1,W01,1207,W16,1250,1207,W01
1,R1W2,W02,1210,W15,1273,1210,W02
2,R1W3,W03,1228,W14,1318,1228,W03
3,R1W4,W04,1260,W13,1233,1260,W04
4,R1W5,W05,1374,W12,1330,1374,W05
5,R1W6,W06,1208,W11,1455,1208,W06
6,R1W7,W07,1393,W10,1177,1393,W07
7,R1W8,W08,1396,W09,1439,1396,W08
8,R1X1,X01,1385,X16,1380,1385,X01
9,R1X2,X02,1433,X15,1267,1433,X02
10,R1X3,X03,1301,X14,1305,1301,X03
11,R1X4,X04,1424,X13,1361,1424,X04
12,R1X5,X05,1449,X12,1246,1246,X12
13,R1X6,X06,1409,X11,1431,1431,X11
14,R1X7,X07,1104,X10,1112,1104,X07
15,R1X8,X08,1234,X09,1116,1116,X09
16,R1Y1,Y01,1328,Y16,1299,1328,Y01
17,R1Y2,Y02,1272,Y15,1335,1272,Y02
18,R1Y3,Y03,1181,Y14,1337,1181,Y03
19,R1Y4,Y04,1326,Y13,1235,1326,Y04
20,R1Y5,Y05,1256,Y12,1338,1256,Y05
21,R1Y6,Y06,1403,Y11,1130,1130,Y11
22,R1Y7,Y07,1412,Y10,1277,1412,Y07
23,R1Y8,Y08,1425,Y09,1229,1229,Y09
24,R1Z1,Z01,1276,Z16,1192,1276,Z01
25,R1Z2,Z02,1314,Z15,1292,1314,Z02
26,R1Z3,Z03,1242,Z14,1325,1242,Z03
27,R1Z4,Z04,1261,Z13,1298,1298,Z13
28,R1Z5,Z05,1268,Z12,1275,1268,Z05
29,R1Z6,Z06,1345,Z11,1120,1120,Z11
...,...,...,...,...,...,...,...
33,R2W2,R1W2,1210,R1W7,1393,1210,R1W2
34,R2W3,R1W3,1228,R1W6,1208,1228,R1W3
35,R2W4,R1W4,1260,R1W5,1374,1260,R1W4
36,R2X1,R1X1,1385,R1X8,1116,1385,R1X1
37,R2X2,R1X2,1433,R1X7,1104,1104,R1X7
38,R2X3,R1X3,1301,R1X6,1431,1301,R1X3
39,R2X4,R1X4,1424,R1X5,1246,1246,R1X5
40,R2Y1,R1Y1,1328,R1Y8,1229,1328,R1Y1
41,R2Y2,R1Y2,1272,R1Y7,1412,1272,R1Y2
42,R2Y3,R1Y3,1181,R1Y6,1130,1130,R1Y6
43,R2Y4,R1Y4,1326,R1Y5,1256,1256,R1Y5
44,R2Z1,R1Z1,1276,R1Z8,1437,1437,R1Z8
45,R2Z2,R1Z2,1314,R1Z7,1323,1314,R1Z2
46,R2Z3,R1Z3,1242,R1Z6,1120,1120,R1Z6
47,R2Z4,R1Z4,1298,R1Z5,1268,1268,R1Z5
48,R3W1,R2W1,1207,R2W4,1260,1207,R2W1
49,R3W2,R2W2,1210,R2W3,1228,1210,R2W2
50,R3X1,R2X1,1385,R2X4,1246,1385,R2X1
51,R3X2,R2X2,1104,R2X3,1301,1301,R2X3
52,R3Y1,R2Y1,1328,R2Y4,1256,1328,R2Y1
53,R3Y2,R2Y2,1272,R2Y3,1130,1272,R2Y2
54,R3Z1,R2Z1,1437,R2Z4,1268,1437,R2Z1
55,R3Z2,R2Z2,1314,R2Z3,1120,1314,R2Z2
56,R4W1,R3W1,1207,R3W2,1210,1207,R3W1
57,R4X1,R3X1,1385,R3X2,1301,1385,R3X1
58,R4Y1,R3Y1,1328,R3Y2,1272,1272,R3Y2
59,R4Z1,R3Z1,1437,R3Z2,1314,1437,R3Z1
60,R5WX,R4W1,1207,R4X1,1385,1207,R4W1
61,R5YZ,R4Y1,1272,R4Z1,1437,1437,R4Z1
62,R6CH,R5WX,1207,R5YZ,1437,1437,R5YZ